### ISSUE TITLE
当一个米游社账户下有两个角色时候，可以选择只推送一个吗?

### ISSUE THREAD

**Issue by licroo** [Xm798/Genshin-Dailynote-Helper#10]
### 问题描述

米游社绑定了官服和b服，b服早就不玩了，又解不了绑定，结果一直推送b服树脂溢出

**Comment by Xm798** [comment]
这个……是个问题，等我研究一下看看

米游社绑定了账号不让解绑真的好烦

**Comment by Xm798** [comment]
加上了，现在可以屏蔽部分角色。

[v2.1.0 serverless](https://github.com/Xm798/Genshin-Dailynote-Helper/releases/tag/v2.1.0)
c4cca49427d290b8dea08b06cb7ec6f803addac6
