### ISSUE TITLE
TG_USER_ID支持多用户提醒

### ISSUE THREAD

**Issue by quericy** [Xm798/Genshin-Dailynote-Helper#11]
### 问题描述

当前现象：
+ TG_USER_ID只能配置一个，多帐号只能发给一个人或者一个群聊，干扰较大

期望功能：
+ 支持配置多个消息接收者id
+ 支持配置每个帐号对应的消息接受者

**Comment by Xm798** [comment]
1. "支持配置多个消息接收者id"的功能，Telegram api并不支持同时推送给多个接收人/群组，该可以通过推送到群聊曲线实现。
2. "支持配置每个帐号对应的消息接受者"这个功能不方便做对应，比如十个账号有五个接收人，如何指定对应的关系？如果强行支持的话会让配置变得更加复杂，且会破坏当前的配置格式；且本项目定位是提供给个人用的项目而不是公共服务，这个需求不是大众需求，支持该功能的代价过高。如果实在有这个需求可以通过运行多个云函数实例 / docker 容器来实现，以腾讯云云函数为例，在 64MB 内存配置下可以免费运行320,000秒/月，本项目一次的正常运行时间在五秒以下，以5秒计算每天可检查 2133 次，足够配置多个云函数实例以完成该需求。
