### ISSUE TITLE
自定义推送

### ISSUE THREAD

**Issue by windskyxb** [Xm798/Genshin-Dailynote-Helper#18]
### 问题描述

请问是否可以添加一个设置自定义推送的选项？

**Comment by Xm798** [comment]
可以考虑，但要过段时间，欢迎 PR

**Comment by Xm798** [comment]
已支持，[使用文档](https://github.com/Xm798/Genshin-Dailynote-Helper/blob/master/docs/Push-method-configuration_ZH.md#13-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A8%E9%80%81)
