### ISSUE TITLE
add utf-8 support for docker

### ISSUE THREAD

**Issue by quericy** [Xm798/Genshin-Dailynote-Helper#22]
#### Problem
+  couldn't show utf-8 logs in docker
![image](https://i.imgur.com/EBoJLDU.png)

#### Suggestion
+ add musl-locales in `Dockerfile`
+ add `LANG=en_US.UTF-8` in docker env/ docker-compose.yml

**Comment by Xm798** [comment]
It worked for me on Synology and Debian, and the `LANG` environment variable was set to `C.UTF-8`. I have not set this variable manually so I don't know if it was set by the docker itself. 

![image](https://user-images.githubusercontent.com/48074861/158166291-87af498c-450e-4a33-b42a-45980a341847.png)
