### ISSUE TITLE
配置文件有误

### ISSUE THREAD

**Issue by Project-Rin** [Xm798/Genshin-Dailynote-Helper#24]
### 问题描述

docker run -d \
-v /PATH-to-YOUR-CONFIG/config.yaml:/app/dailynotehelper/config/config.yaml \
--env TZ=Asia/Shanghai
--restart=always \
--name=genshin-dailynote-helper \
xm798/genshin-dailynote-helper:latest

-->

docker run -d \
-v /PATH-to-YOUR-CONFIG:/app/dailynotehelper/configl \
--env TZ=Asia/Shanghai ‘\’
--restart=always \
--name=genshin-dailynote-helper \
xm798/genshin-dailynote-helper:latest

时区上海那缺了一个反斜杠“\”
印象中 docker 的环境变量是是文件夹而不是文件
我自己用文件夹没报错，用文件的话会新建一个config.yaml的文件夹
系统是 Ubuntu

### 运行环境

Docker

### 程序版本

v2.1.6.1

**Comment by Xm798** [comment]
映射文件是没有问题的，如果有问题的话一般是绝对路径错了，见 docker [官方文档](https://docs.docker.com/storage/volumes/#create-and-manage-volumes) 和 StackOverflow [相关讨论](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume)。
> If you start a container with a volume that does not yet exist, Docker creates the volume for you. 
![image](https://user-images.githubusercontent.com/48074861/159392386-dab52603-966f-4d7b-a619-5403c6a0542c.png)

时区一行缺少换行标记的错误已修复，感谢！
