### ISSUE TITLE
在阿里云函数上用telegram bot 每次都是提醒今日委托未完成

### ISSUE THREAD

**Issue by zmmx** [Xm798/Genshin-Dailynote-Helper#32]
### 问题描述

但是我任务已经做完了  显示 今日委托任务：0 / 4   奖励未领取  港澳台服

### 运行环境

云函数

### 程序版本

v2.1.7.5

**Comment by Xm798** [comment]
1. 找凯瑟琳领取一下额外奖励呢？
2. 如果已领取还提示的话，请登录Hoyolab看一下实时便笺，毕竟我们不生产数据，我们只做数据的搬运工~

**Comment by zmmx** [comment]
![S20504-22143468.png](https://user-images.githubusercontent.com/35140632/166700391-a6b10db4-91fa-4387-862b-7ce395803f97.png)打开看了下是这样的

**Comment by Xm798** [comment]
这是去其他人世界做的？凯瑟琳的额外奖励领了没……
如果确认已经领了的话，那就是国际服接口有点问题，之前也有人反馈过同样的问题。国际服便笺确实不如国服稳定。。。。

这是我国服和国际服小号的便笺

![image](https://user-images.githubusercontent.com/48074861/166701289-81925a79-0628-4ed7-bd0e-1a52dbbd3def.png)

![image](https://user-images.githubusercontent.com/48074861/166701331-a83872be-ca5f-47a6-b016-8404e6c735a0.png)

**Comment by zmmx** [comment]
委托都是在自己世界做的，看来这个是hoyolab接口的问题，那我只能先屏蔽委托提醒了。
