### ISSUE TITLE
能不能每隔一段时间就强制推送呢？

### ISSUE THREAD

**Issue by stevened7246** [Xm798/Genshin-Dailynote-Helper#36]
### 问题描述

如题，对推送产生依赖性后完全没有去app上看讯息的想法
<del>虽然有可能没有必要，但是我相信大佬一定会加功能的~</del>

**Comment by Xm798** [comment]
我对这个工具的定位是提醒上线的一个工具，定时强制推送会让推送的价值变低，无法获得最高优先级的上班警告，甚至会让人想要免打扰消息，让这个工具存在的意义降低。同时，定时的灵活性也不太够，多数时候并不是每个小时都想了解便笺信息的。

如果是想要随时不打开APP查看便笺信息话可以根据你的平台选择不同的方案，例如[iOS](https://ngabbs.com/read.php?tid=29801567)和[安卓端](https://ngabbs.com/read.php?tid=31619446)可用的桌面小部件，Windows端（当然不止Windows）可用的[浏览器插件](https://github.com/daidr/paimon-webext)、MacOS端可用的[任务栏插件](https://github.com/spencerwooo/PaimonMenuBar)。

我目前也是多个工具同时使用的，浏览器插件和手机桌面小部件供我偶尔主动查看使用（频率不高，一天不会超过十次），这个工具在树脂溢出或者晚上睡前忘做委托的时候直接发送不可能被我忽略的强提醒催我上线，各司其职，挺好的。

**Comment by Xm798** [comment]
当然如果是实在想要它定时推送的话，可以将树脂阈值改为1，这样就能每次运行都推送了（

**Comment by stevened7246** [comment]
> 当然如果是实在想要它定时推送的话，可以将树脂阈值改为1，这样就能每次运行都推送了（

感谢感谢~就是可惜安卓的没有国际服罢了
