### ISSUE TITLE
腾讯云测试成功了，不过有点小问题。

### ISSUE THREAD

**Issue by hdlxjm** [Xm798/Genshin-Dailynote-Helper#4]
我一开始使用了同一个浏览器对两个米游社账号读取了cookies，先登录读取的账号A，后登录读取的账号B，并粘贴到了yaml文件中，部署测试时发现A账号会显示登录失败。后来发现可能是因为在浏览器中后登录的账号B会使得A的cookies失效，于是使用了两个浏览器分别读取A和B的cookies，部署测试后都登录成功了。
另外，部署测试成功后就不需要其他操作，等着收微信提醒就可以了是吧？
PS：是否可以增加对不同账号自定义提醒内容，比如我的B账号不需要提醒洞天宝钱但是A账号需要。

**Comment by Xm798** [comment]
1. 多个账号登录需要清除 Cookie 或者开隐身模式，或者使用多个浏览器，否则 Cookie 会相互影响。
2. 测试成功后就不需要其他操作了，它会按照你触发器设置的时间定时触发。
3. 这个不支持，支持这个会让配置文件变得更复杂，有这个需求的话建议部署两个云函数。云函数的免费配额是足够的。

**Comment by hdlxjm** [comment]
了解，感谢！

**Comment by Xm798** [comment]
主要是点了注销账号就会导致原来的 cookie 失效，所以推荐用隐身模式获取，然后直接关掉浏览器（不要点注销账号），再开隐身模式获取另一个。
