### ISSUE TITLE
云函数部署后重复推送的问题

### ISSUE THREAD

**Issue by Immortal68** [Xm798/Genshin-Dailynote-Helper#6]
云函数部署成功后，设置了`Push Plus`推送渠道，于**5:00**开始，分别在**5:00,5:15,5:30,5:45**四个时间点重复推送多次，达到PushPlus单日推送限制200条阈值后便无法再接收任何内容。

**Comment by Xm798** [comment]
麻烦查看一下日志，是程序内触发了多次推送还是云函数多次执行？麻烦贴一下完整的日志看一下，我这边没有遇到这样的问题。

**Comment by Immortal68** [comment]
应该是云函数多次执行导致的
### START RequestId:cb1a0014-fc9b-4d8c-887a-46d7a9de6e95

-------------------------------------------------------------
|                Genshin Dailynote Helper                   |
-------------------------------------------------------------
| Current Version: v2.0.0                                   |
| Last Update: Feb 09, 2022                                 |
| Github: https://github.com/Xm798/Genshin-Dailynote-Helper |
-------------------------------------------------------------

-------------------------
🗝️  当前配置了1个账号，正在执行第1个
正在获取角色信息
Starting new HTTPS connection (1): api-takumi.mihoyo.com:443
https://api-takumi.mihoyo.com:443 "GET /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn HTTP/1.1" 200 207
获取到1个角色...
第1个角色，198332353 上杉稚
Starting new HTTPS connection (1): api-takumi-record.mihoyo.com:443
https://api-takumi-record.mihoyo.com:443 "GET /game_record/app/genshin/api/dailyNote?role_id=198332353&server=cn_gf01 HTTP/1.1" 200 1219
🔔今日委托未完成，发送提醒。
✅树脂检查结束，当前树脂74，未到提醒临界值。
✅洞天宝钱检查结束，未溢出。
✅探索派遣检查结束，不存在完成的探索派遣。
✅睡眠期间树脂不会溢出，放心休息。
Starting new HTTPS connection (1): www.pushplus.plus:443
https://www.pushplus.plus:443 "POST /send HTTP/1.1" 200 None
pushplus 😳
<Response [200]>
Starting new HTTPS connection (1): api2.pushdeer.com:443
https://api2.pushdeer.com:443 "POST /message/push HTTP/1.1" 200 None
Pushdeer 🥳


本轮运行结束，等待下次检查...
Response RequestId:cb1a0014-fc9b-4d8c-887a-46d7a9de6e95 RetMsg:null
END RequestId:cb1a0014-fc9b-4d8c-887a-46d7a9de6e95
Report RequestId:cb1a0014-fc9b-4d8c-887a-46d7a9de6e95 Duration:921ms Memory:128MB MemUsage:21.653717MB


[这里是云函数执行日志记录图片](https://s3.bmp.ovh/imgs/2022/02/0911b95df9eb189d.png)可以看到重复执行

**Comment by Xm798** [comment]
那需要检查一下触发器设置，多次触发和该项目没有关系的。

**Comment by Immortal68** [comment]
> 那需要检查一下触发器设置，多次触发和该项目没有关系的。

触发器设置15/30/60分钟我都尝试过，更换到了企业微信推送，发现还是在所需要触发时间点内重复运行，例如7点触发，项目在19:00-19:01这60秒每秒触发了一次，导致每秒都推送一次。我仔细检查了配置文件并重新部署了云函数，应该不存在填写上的问题，部署测试也是正常的只推送一次，但是实际运行就存在问题。

**Comment by Immortal68** [comment]
> 那需要检查一下触发器设置，多次触发和该项目没有关系的。

刚刚7点推送次数有问题，8点推送情况正常，我再持续关注一段时间

**Comment by Xm798** [comment]
我这边创建了一个触发器`0 24 */1 * * * *`尝试了一下，倒是没有发现调用异常的现象。
![image](https://user-images.githubusercontent.com/48074861/153590990-a9f45b9d-d9f1-450e-93b5-8d1f191bd818.png)
![image](https://user-images.githubusercontent.com/48074861/153591024-97f294fe-2c28-4509-88c9-cf763f33f67d.png)

如果说是多次调用的话，肯定是腾讯云云函数触发方面的问题，因为何时触发是外部事件，程序是无法控制的。还有问题可以用腾讯云自带的每小时触发试一下，再出现问题的话就可以给腾讯云直接提工单，看到底是啥情况。

![image](https://user-images.githubusercontent.com/48074861/153591241-d5efe8a9-d3d9-48ad-9cbd-202b97712bfa.png)

**Comment by Immortal68** [comment]
> p.s. issue 中有账号信息，我帮你编辑掉了。
万分感谢！！！现在推送都是正常的了！

**Comment by Xm798** [comment]
破案了，我仔细看了一眼文档，是我文档写错了，麻了……
